before:
  hooks:
    - go test ./...

builds:
  - env: [CGO_ENABLED=0]
    ldflags:
      - '-s -w -X "github.com/nslhb/terraform-k8s/version.Version={{ .Version }}" -X "github.com/nslhb/terraform-k8s/version.Prerelease="'
    goos:
      - linux
      - windows
      - darwin
    targets:
      - amd64
      - arm64

archives:
  -
    format: zip
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    files: # Avoid packaging any extra (default) files
      - none*

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  skip: true
  
  
dockers:
  - image_templates: ["ghcr.io/nslhb/terraform-k8s:{{ .Version }}-{{ .Arch }}"]
    ids: [example]
    goarch: "{{ .Arch }}"
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/nslhb/terraform-k8s
      - --label=org.opencontainers.image.source=https://github.com/nslhb/terraform-k8s
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/nslhb/terraform-k8s:{{ .Version }}
    image_templates:
      - ghcr.io/nslhb/terraform-k8s:{{ .Version }}-{{ .Arch }}
      - ghcr.io/nslhb/terraform-k8s:{{ .Version }}-{{ .Arch }}
