# permissions for end users to edit workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-editor-role
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - services/finalizers
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
  verbs:
    - '*'
#  - apiGroups:
#      - apps
#    resources:
#      - deployments
#      - daemonsets
#      - replicasets
#      - statefulsets
#    verbs:
#      - '*'
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.terraform.io
  resources:
  - workspaces/status
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch